<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.Module.Targets" Version="2.2.1" />
    <PackageReference Include="OrchardCore.ContentManagement" Version="2.2.1" />
    <PackageReference Include="OrchardCore.ContentManagement.Display" Version="2.2.1" />
    <PackageReference Include="OrchardCore.Navigation.Core" Version="2.2.1" />
    <PackageReference Include="YesSql.Core" Version="5.4.6" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Compost.Kanban\Compost.Kanban.csproj" />
  </ItemGroup>
</Project>
