<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.Module.Targets" Version="2.2.1" />
    <PackageReference Include="OrchardCore.ContentManagement" Version="2.2.1" />
    <PackageReference Include="OrchardCore.DisplayManagement" Version="2.2.1" />
    <PackageReference Include="OrchardCore.Navigation" Version="2.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Compost.Core\Compost.Core.csproj" />
    <ProjectReference Include="..\Compost.Kanban\Compost.Kanban.csproj" />
  </ItemGroup>

</Project>
