<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.Module.Targets" Version="1.8.2" />
    <PackageReference Include="OrchardCore.ContentManagement" Version="1.8.2" />
    <PackageReference Include="OrchardCore.DisplayManagement" Version="1.8.2" />
    <PackageReference Include="OrchardCore.Navigation" Version="1.8.2" />
    <PackageReference Include="System.Text.Json" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Compost.Core\Compost.Core.csproj" />
    <ProjectReference Include="..\Compost.Kanban\Compost.Kanban.csproj" />
  </ItemGroup>

</Project>
